### PR TITLE
Allow DNS resolve only to VPN remotes

### PR DESCRIPTION
**Pull request by davebv**
This patch will allow only DNS queries to the remotes in the $conf file if VPN is disconnected.
The rule to allow destination port 53 has been extended to filter for string only present in the `remote <VPN_SERVER> port and will filter out other queries not matching the <VPN_SERVER>

This would fix DNS leaks if VPN is not connected

### CODE REVIEW

**Comment by dperson** [comment]
This won't let the original connection come up if DNS doesn't resolve.

**Comment by dperson** [comment]
This won't let the original connection come up if DNS doesn't resolve.

**Comment by davebv** [comment]
> This won't let the original connection come up if DNS doesn't resolve.

Hi, I am not sure what you mean. If VPN connection is not active, it will only resolve the VPN remote host, extracted from the vpn configuration. Once connection is established, it shall resolve all requests.

**Comment by dperson** [comment]
Sorry it was really late when I read it, you are correct.

I'm not sure if I feel that DNS needs to be locked down to that extent though...

**Pull request closed without merging**
