### PR TITLE
Bringing back the DNS leak fix

### PR DESCRIPTION
**Pull request by 5andr0**
I saw you reverted this fix because you thought it broke vpnportforward in [#284](https://github.com/dperson/openvpn-client/issues/284)
But it actually didn't.  
I know you added $firewall_cust, but this fix should be default and not custom!

You forgot to revert ${ext_args[*]} to $ext_args since its not an array anymore.

Stay safe!

### CODE REVIEW

**Comment by arpitgupta** [comment]
Question: Will i still be able to forward port 53 in order to my personal dns servers with this fix?

**Comment by 5andr0** [comment]
> Question: Will i still be able to forward port 53 in order to my personal dns servers with this fix?

@arpitgupta 
Sure, that won't be affected. 
When the vpn is down and firewall is set, only the openvpn process can send requests to resolve the vpn server domain. It doesn't matter where these requests go as long as they come from the openvpn process only.
You can postroute to any other IP/port or just set your own DNS with the docker --dns option.

If DNS requests wouldn't be restricted by the openvpn process, all DNS requests from attached containers would be sent to your provider while the vpn is down, even when firewall is set.

**Comment by arpitgupta** [comment]
thanks for the explanation @5andr0 . I am just getting started with using this image and was curious,

**Comment by dperson** [comment]
@5andr0 I did get people having broken connections (and even had some myself due to a separate issue, in addition to the issue below) right after this change went in originally. That's when I started modifying / removing bits. Please see my comments below:

1) I'm not sure your rules do what you think. Moving the port 53 rule `iptables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT` is fine... but I don't know why you're moving it into 2 locations (line 103 and 107)?

2) In the `if` statement:
```
    if grep -Fq "127.0.0.11" /etc/resolv.conf; then
        iptables -A OUTPUT -d 127.0.0.11 -m owner --gid-owner vpn -j ACCEPT || 
            iptables -A OUTPUT -d 127.0.0.11 -j ACCEPT
        iptables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT; fi
```
If 127.0.0.11 is in /etc/resolv.conf it will add the iptables rule in the second line (allowing only the VPN to query the default docker DNS IP) if it runs without error, otherwise the third line (full access to the default docker DNS IP). The fourth line then allows all DNS queries... is that meant to be part of an `else` statement?

3) The `ext_args` rules:
```
    ext_args+=" --route-up '/sbin/iptables -A OUTPUT -d 127.0.0.11 -j ACCEPT'"	
    ext_args+=" --route-pre-down"	
    ext_args+=" '/bin/sh -c \"iptables -D OUTPUT -d 127.0.0.11 -j ACCEPT\"'"
```
  a) When the route is up, it allows any process to connect to the default docker DNS IP, with the **exact same rule** that was potentially added from the `if` statement above.
  b) When the route is being brought down, remove the rule that was added when it came up OR does in remove the one from the `if` statement OR both?
  c) Why is the down rule wrapped in the `'/bin/sh -c \"\"'` when the up rule isn't?

4) What if someone has an IPv6 DNS server configured? AFAICT (As Far As I Can Tell), you will block all DNS for them, unless their kernel doesn't support `-m owner --gid-owner vpn`.

All of this is just to make sure DNS is broken for other processes when the VPN is down if, and only if, the default docker custom network DNS is being used. When they can't make any other connections, what does it matter if they can look up DNS?

**Comment by 5andr0** [comment]
@dperson 

_1. I'm not sure your rules do what you think. Moving the port 53 rule `iptables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT` is fine... but I don't know why you're moving it into 2 locations (line 103 and 107)?_

line 103: if filtering by --gid-owner fails (block after line 100 || is executed) then we have to allow all DNS requests because we can't filter by the running openvpn process gid.

line 100: if filtering is available, all DNS requests from any other DNS except 127.0.0.11 will be allowed by this rule: `iptables -A OUTPUT -p udp -m owner --gid-owner vpn -j ACCEPT ` 
if the requests are sent from the openvpn process with its gid vpn

line 104-107: if _127.0.0.11_ is set as DNS, we can't filter DNS requests from the eDNS itself because they are sent from the eDNS process which is running as gid 0. This is why we have to generally allow all DNS requests from the eDNS process with this rule: `iptables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT;`
But luckily we can filter the DNS requests which are sent from the openvpn process to the eDNS itself. But these are rerouted to another dynamic port of the eDNS like this:
```
# iptables -nvL -t nat  
.....  
Chain DOCKER_OUTPUT (1 references)  
 pkts bytes target     prot opt in     out     source               destination  
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            127.0.0.11           tcp dpt:53 to:127.0.0.11:45997  
    0     0 DNAT       udp  --  *      *       0.0.0.0/0            127.0.0.11           udp dpt:53 to:127.0.0.11:49614  

Chain DOCKER_POSTROUTING (1 references)  
 pkts bytes target     prot opt in     out     source               destination  
    0     0 SNAT       tcp  --  *      *       127.0.0.11           0.0.0.0/0            tcp spt:45997 to::53  
    0     0 SNAT       udp  --  *      *       127.0.0.11           0.0.0.0/0            udp spt:49614 to::53
```
This is why i have to allow all ports to the eDNS, but i can filter the requests by gid vpn:
`iptables -A OUTPUT -d 127.0.0.11 -m owner --gid-owner vpn -j ACCEPT`
again: if --gid-owner filtering is not available we have to allow all the requests:
`|| iptables -A OUTPUT -d 127.0.0.11 -j ACCEPT`

_2. The fourth line then allows all DNS queries... is that meant to be part of an else statement (it's also the second copy mentioned above)?_

As explained in 1: it will allow all DNS queries from the eDNS itself, but it won't allow all requests from the openvpn process because these are rerouted to another port (see DOCKER_POSTROUTING above) and therefore not catched by --dport 53

_Why is this even needed at all if `--gid-owner vpn` works then the VPN can already connect to anything with TCP/UDP and if it's not supported there's the rule that's moved to 103 as mentioned above?_
As explained, --gid-owner filtering doesn't work for queries coming from the eDNS because this runs as gid 0 and NOT vpn. That's why we have to filter the queries that are coming from the openvpn to the eDNS but then generally allow all requests from the eDNS (which are only sent when the DNS requests from openvpn are passed to the eDNS)

_3. The `ext_args` rules:
```
    ext_args+=" --route-up '/sbin/iptables -A OUTPUT -d 127.0.0.11 -j ACCEPT'"	
    ext_args+=" --route-pre-down"	
    ext_args+=" '/bin/sh -c \"iptables -D OUTPUT -d 127.0.0.11 -j ACCEPT\"'"
```
When the route is up, it allows any process to connect to the default docker DNS IP, with the exact same rule that was potentially added from the if statement above._

This is true and necessary, so that all other attached containers can send DNS requests when vpn is up. When vpn is up, all DNS requests from the eDNS 127.0.0.11 are now routed over the vpn network. 

_When the route is being brought down, remove the rule that was added when it came up OR does in remove the one from the if statement OR both?_

Good point. It would also remove the rule, which is needed when --gid-owner filtering is not available. I will write a fix for that and commit asap. 

_Why is the down rule wrapped in the '/bin/sh -c \"\"' when the up rule isn't?_

The down script command had to be called via `sh -c` because this discards [multiple arguments](https://github.com/OpenVPN/openvpn/blob/3b06b57d9f1d972ec16f0893d06697439c1bb1fe/src/openvpn/init.c#L177) that are added by openvpn, which caused an error as iptable options. All arguments were passed inside an argv array to [execve(cmd, argv, envp);](https://github.com/OpenVPN/openvpn/blob/01a3c876d4911ff7ea82b04edeb43defdebc69d7/src/openvpn/run_command.c#L153) so commenting them out by ;# was no option.

openvpn doesn't pass additional arguments for the up script.

_4. What if someone has an IPv6 DNS server configured? AFAICT (As Far As I Can Tell), you will block all DNS for them, unless their kernel doesn't support -m owner --gid-owner vpn._

in a IPv6 custom network, docker still uses 127.0.0.11 for container hostname resolving and IPv4 DNS requests, but the IPv6 DNS from --dns or the host is inserted directly into /etc/resolv.conf, so all IPv6 DNS requests can be filtered by --gid-owner vpn

Since there is no eDNS for IPv6 DNS requests, there's no special treatment.
```
ip6tables -A OUTPUT -p udp -m owner --gid-owner vpn -j ACCEPT 2>/dev/null||{
        ip6tables -A OUTPUT -p tcp -m tcp --dport $port -j ACCEPT 2>/dev/null	        ip6tables -A OUTPUT -p tcp -m tcp --dport $port -j ACCEPT 2>/dev/null
        ip6tables -A OUTPUT -p udp -m udp --dport $port -j ACCEPT 2>/dev/null; }	        ip6tables -A OUTPUT -p udp -m udp --dport $port -j ACCEPT 2>/dev/null
        ip6tables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT 2>/dev/null; }
```

If --gid-owner filtering is available, the requests can be filtered by gid vpn, otherwise all IPv6 requests are allowed by:
`ip6tables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT 2>/dev/null; `

_All of this is just to make sure DNS is broken for other processes when the VPN is down if, and only if, the default docker custom network DNS is being used. When they can't make any other connections, what does it matter if they can look up DNS?_
[https://en.wikipedia.org/wiki/DNS_leak](https://en.wikipedia.org/wiki/DNS_leak)
You might think, this is useless, but most of your customers are using this for obfuscation and most likely would like to obfuscate their DNS requests aswell.

Here are a few reasons:
- In times of SSL, all the content you send is encrypted anyway. So the only thing that matters is in fact DNS requests:
[is-your-isp-selling-your-data](https://protonvpn.com/blog/is-your-isp-selling-your-data/)
- What if you live in a campus or an army base and the only internet available is from your employer, which can and will monitor your DNS requests
- The NSA has ways to footprint your connection based on connections you make. If you don't use your vpn's DNS servers and start all containers with one docker-compose up, they will all make their DNS requests before vpn is connected and if they can't establish connections they will retry the exact same requests when the vpn is up, with your vpn IP to the exact same DNS you configured.
- Not everyone is living in a free democratic country. Somewhere in this world, even a few DNS requests to the wrong domains can give you big trouble.

Yes, this might be paranoid, but some people rely on it or just want it. That's why all the VPN providers offer anti DNS-Leak techniques in their software.

Having a userbase of half a million on docker-hub comes with great responsibility.

I still don't see any reason how these rules would break any vpn connection? They won't interfere with anything besides the vpnportforward, which is fixed.

If anyone is interested in the full explanation:
[Fix DNS leak #280](https://github.com/dperson/openvpn-client/pull/280)

**Comment by dperson** [comment]
1. **I'm not sure your rules do what you think.**
**LINE 100**: What makes you think this doesn't allow DNS to 127.0.0.11?
```
iptables -A OUTPUT -p udp -m owner --gid-owner vpn -j ACCEPT 
```
**LINE 107**: So if the DNAT / SNAT take place before the firewall rule evaluation this will do what you're saying I think (but I can't remember for sure what the order they take place in).
```
iptables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT
```
2. **Already covered as noted.**
3. **The ext_args rules.**
**Why is the down rule wrapped in the '/bin/sh -c ""' when the up rule isn't?**
So it was appending extra arguments when calling it for bringing the route down? If that's the case, could you escape the up rule in a similar manner, just in case it will start doing the same with certain configuration files (I can't remember if any route info can be in a client configuration or know if it might be allowed in the future)? Thanks.
4. **What if someone has an IPv6 DNS server configured? AFAICT (As Far As I Can Tell), you will block all DNS for them, unless their kernel doesn't support -m owner --gid-owner vpn.**
Again, Docker isn't the only way to run the containers, they can and are used on Kubernetes and Podman. What you say works for bringing up the VPN, and if `-m owner --gid-owner` is broken. But what if '-m owner --gid-owner' works and DNS is only available via IPv6?
**All of this is just to make sure DNS is broken for other processes when the VPN is down if, and only if, the default docker custom network DNS is being used. When they can't make any other connections, what does it matter if they can look up DNS?**
Okay good enough point about the leaks.
**The problem with this is that in a default linux environment ip6tables won't work, even when IPv6 is enabled.**
What modern system doesn't have IPv6 and a firewall enabled by default? What message do you want to output to the user of the container (if they look at the logs)?

**Comment by 5andr0** [comment]
**1. LINE 100: What makes you think this doesn't allow DNS to 127.0.0.11?
iptables -A OUTPUT -p udp -m owner --gid-owner vpn -j ACCEPT**
This rule does allow DNS **TO** _127.0.0.11_ but not from the eDNS process because this runs as uid 0.
For clarification: the eDNS runs inside your container listening on a dynamic port on 127.0.0.11 which is higher than 53

Here's a trace of a DNS request:
`openvpn -->iptables:gid(vpn):port(49614)--> eDNS 127.0.0.11:49614  -->iptables:gid(0):port(53)-->remote DNS 8.8.8.8:53`

So yes, DNAT/SNAT comes before firewall and therefore we can allow port 53 while still filtering packets to eDNS on port 49614 (dynamic, based on the postroute posted here)

3. [openvpn/init.c](https://github.com/OpenVPN/openvpn/blob/3b06b57d9f1d972ec16f0893d06697439c1bb1fe/src/openvpn/init.c#L1690)
```
argv_parse_cmd(&argv, options->route_script);
openvpn_run_script(&argv, es, 0, "--route-up");
```
Right now, there are no additional args with --route-up, but i'll add a commit to future proof it in case they change it. Fixed with this commit: [f608c38](https://github.com/dperson/openvpn-client/pull/290/commits/f608c38a0fbe661e72f4f140f6c705dd2480df62)

**4. Again, Docker isn't the only way to run the containers, they can and are used on Kubernetes and Podman. What you say works for bringing up the VPN, and if -m owner --gid-owner is broken. But what if -m owner --gid-owner works and DNS is only available via IPv6?**

I know, there are other implementations, but this fix is only active and needed with the moby embedded DNS. For any other configuration there are still the default rules:

```
    ip6tables -A OUTPUT -p udp -m owner --gid-owner vpn -j ACCEPT 2>/dev/null||{
        ip6tables -A OUTPUT -p tcp -m tcp --dport $port -j ACCEPT 2>/dev/null
        ip6tables -A OUTPUT -p udp -m udp --dport $port -j ACCEPT 2>/dev/null
        ip6tables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT 2>/dev/null; }
```
if _--gid-owner_ is not available, then all DNS port 53 traffic and ovpn traffic is allowed. If _--gid-owner_ works, then all traffic including DNS is allowed anyway by the openvpn. This is true for IPv6 and IPv4.
Once vpn is up, everything including remote DNS is routed through tap/tun which is accepted in the firewall rules:
```
ip6tables -A OUTPUT -o tap+ -j ACCEPT 2>/dev/null
ip6tables -A OUTPUT -o tun+ -j ACCEPT 2>/dev/null
iptables -A OUTPUT -o tap+ -j ACCEPT
iptables -A OUTPUT -o tun+ -j ACCEPT
```

**What modern system doesn't have IPv6 and a firewall enabled by default? What message do you want to output to the user of the container (if they look at the logs)?**
ubuntu has ip6table_filter up by default. But debian (most popular Linux Server Distro) has it down by default. My suggestion: [238db9c](https://github.com/dperson/openvpn-client/pull/290/commits/238db9ca80300777a9d91dab19f8f627dc40d1cb)

**Comment by dperson** [comment]
**1. Okay sorry for being slow on this one, and thanks for the explanation.**

**3. Thanks for including it.**

**4. But what if -m owner --gid-owner works and DNS is only available via IPv6?**
You're assuming that someone has their VPN configured to avoid DNS leaks (IE that DNS will go over the VPN). I have seen peoples configurations that don't have that enabled, and they keep using their local DNS. If that's the case, and their DNS is IPv6 it will break.

**What modern system doesn't have IPv6 and a firewall enabled by default? What message do you want to output to the user of the container (if they look at the logs)?**
Ugh, okay I like the message :+1: 

From what you're saying, the `ip6tables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT 2>/dev/null` and `iptables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT` rules don't actually let DNS traffic through when the docker/moby embedded DNS is in use (which is likely the most common case, and the one you're trying to fix). AFAICT (As Far As I Can Tell), it doesn't matter where they are in the order of the rules as you're not adding a `DROP` or `REJECT` rule. You're adding it back potentially twice for IPv4 and at least once. In the case that `-m owner --gid-owner` is broken, I'm pretty sure we're not breaking anything. I'm not sure (as stated above) we aren't breaking at least some use cases for IPv6.

Why don't we just leave the port 53 rules in place where they were, and not add line 116?

**Comment by 5andr0** [comment]
We are slowly getting there. Better not rush and play through every scenario.

**Why don't we just leave the port 53 rules in place where they were, and not add line 116?**
Then we would have DNS leaks again for any configuration besides embedded DNS if we allowed port 53, even when `--gid-owner` is available. You are right about the double rule though, here's my fix: [d68ade8](https://github.com/dperson/openvpn-client/pull/290/commits/d68ade83abdc74061f892635fe9ba42f29246b3a)

**4. But what if -m owner --gid-owner works and DNS is only available via IPv6?**
local DNS isn't working anyway because containers can't access the local network, but this has nothing to do with these rules here.

I tested all kinds of IPv6 configurations with docker. Here are some of my findings:
Host with IPv6, and vpn with IPv4 + IPv6 (airvpn) + local DNS servers

**IPv6 custom network:**
- **dns: ["8.8.8.8"]**
`nameserver 127.0.0.11` # IPv6 AAAA records resolved over 8.8.8.8
No IPv6 DNS entry in **/etc/resolv.conf** !
- **no dns specified**
`nameserver 127.0.0.11` # IPv4 resolved over host DNS, unreachable if local
`nameserver fd00::...` # if vpn has IPv6, all requests are resolved over the IPv6 DNS by default!
Requests fail when vpn has IPv6 and IPv6 DNS is local, even when IPv4 DNS is public
- **dns: ["8.8.8.8","2001:4860:4860::8888"]** # google public IPv6 DNS
`nameserver 127.0.0.11` # eDNS uses 8.8.8.8 externally
`nameserver 2001:4860:4860::8888`
No problems here, public DNS routed over vpn

**docker bridge network:**
- **dns: ["8.8.8.8"]**
`nameserver 8.8.8.8` # IPv6 AAAA records resolved over 8.8.8.8
- **no dns specified**
`nameserver 192.168.0.1` # unreachable
`nameserver fd00::...` # same as above with eDNS, unreachable
- **dns: ["8.8.8.8","2001:4860:4860::8888"]** # google public IPv6 DNS
`nameserver 8.8.8.8` 
`nameserver 2001:4860:4860::8888`

It's very important to note that this is the default behavior, regardless of this DNS leak fix.
Local DNS just won't work, even without the firewall because the local host net can't be reached from containers.
You could add a note in your readme's DNS Issues section to add `--dns 2001:4860:4860::8888` if they have IPv6 only without a public DNS.

I know, i just posted docker tests, but everyone using an alternative like kubernetes knows their shit and that local DNS can't be reached from their containers.

For those who use **--net=host** to vpn their host, this fix won't interfere because the host network and even its local DNS would be accepted by this rule:
**ip(6)tables -A FORWARD -s ${docker(6)_network} -j ACCEPT**
This rule would also allow DNS leaks, but whoever wants to use **--net=host** has to live with that since it's an extremely rare case.
Running your own containerized DNS is also still working because of this rule, but you would have to detach it from the vpn container or add custom firewall rules.

**Comment by dperson** [comment]
@5andr0 I didn't mean the local network the docker server is on so much as the local network for the containers DNS. Thinking of the original (legacy) docker bridge and it's DNS. But there is already a rule to allow access to it. Sorry if I wasn't clear. Thanks for the changes and working with me. Merging now.

**Comment by arpitgupta** [comment]
fyi i deployed latest image a5912b18ee0b and am assuming that it has this fix. I am no longer able to use local dns. I was forwarding port 53 on the openvpn client container. fwiw my setup is a bit different with macvlan network which as i understand is not explicitly supported by this image so it might not be an issue for others. lmk if you would like more info.

**Comment by 5andr0** [comment]
@arpitgupta Can you share more information on that please? And maybe try to accept connections to your DNS with the /vpn/.firewall_cust file. But add a debug echo at the end of the file to make sure the rules are executed. Or just for testing add the rules in a interactive container bash and see if it works then.
```
iptables -A OUTPUT -d ${your dns} -j ACCEPT
```
or ip6tables for ipv6.
Your docker config+forward rule and output of `ip route` and `ip -6 route` and `cat /etc/resolv.conf` would help.
Is your DNS attached to the vpn network? If that's the case you will need these rules:
```
iptables -A OUTPUT -s ${your dns} -j ACCEPT
#or
iptables -A OUTPUT -p udp -m udp --dport 53 -j ACCEPT
```

**Comment by arpitgupta** [comment]
@5andr0  will try this out. I have been reading the code to try to understand how this is working. Wanted to check if my setup was correct earlier or my be it was working because of dns leak. In my compose file i would just port '53:53' to open it up but was not sending any `VPNPORTS` env var. So i am wondering if i need to both open the port and set the env var for this to work? Also cant figure out what format to set the env var to would it be something like this
```
VPNPORT: 'P1 udp'
VPNPORT:_2 'P1 tcp'
....
```

Or is there a way to specify this for multiple ports in one value?

**Comment by arpitgupta** [comment]
Adding the custom firewall rule did the trick
```
iptables -A OUTPUT -d 192.168.1.253 -j ACCEPT
iptables -A OUTPUT -d 192.168.1.63 -j ACCEPT
```

> Is your DNS attached to the vpn network? 
It is but that is controlled by my router.

I also tried setting the following 2 env vars
```
VPNPORT: '53;tcp;53;udp'
VPNPORT_2: '53;udp'
```

and following ports
```
ports:
      # allow me to use local dns
      - 53:53/tcp
      - 53:53/udp
```

But this would not resolve the dns. Once i added the custom firewall rules file it worked and i did not need to set the `VPNPORT*` env vars.

**Comment by arpitgupta** [comment]
Did some more testing. If i only have the following env var in the settings
```
VPNPORT: '53;tcp'
```

Then it works. I forward both udp and tcp then then dns resolution does not work.

**Comment by 5andr0** [comment]
@arpitgupta Please be more specific of what exactly you want to achieve here.
Run a DNS server over VPN and access the DNS port over the IP of the docker container host?
Or run a DNS server over VPN and access the DNS port over the IP of your vpn network? Then you would need port forwarding with VPNPORT which only takes one port and one protocol like that: VPNPORT: '53;udp'

This is really weird to me why you needed these rules in the first place. These should be covered by
iptables -A OUTPUT -d ${docker_network} -j ACCEPT
where ${docker_network} is
```
docker_network="$(ip -o addr show dev eth0|awk '$3 == "inet" {print $4}')"
```
which should be `192.168.1.0/24` and therefore include your DNS ips.
Can you please run these commands and give us the output:
```
ip -o addr show dev eth0|awk '$3 == "inet" {print $4}')
ip -o addr show dev eth0
iptables -L
```

**Comment by arpitgupta** [comment]
@5andr0

`192.168.1.242` is the ip i assigned this container on a macvlan network.

```
bash-5.0# ip -o addr show dev eth0|awk '$3 == "inet" {print $4}'
192.168.1.242/24
bash-5.0# 
```

```
bash-5.0# ip -o addr show dev eth0
289: eth0    inet 192.168.1.242/24 brd 192.168.1.255 scope global eth0\       valid_lft forever preferred_lft forever
bash-5.0# 
```

```
bash-5.0# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
bash-5.0# 
```

I had tried adding a route for `192.168.1.0/24` but that would lead to issues with https://github.com/dperson/openvpn-client/issues/291

Regarding the dns setup question, i was just tring out different options to see what would work. I dont need it to be accessed from the vpn ip but either i need to set `VPNPORT` or add the custom firewall rule to achive it.

**Pull request merged**
