### PR TITLE
Added Dockerfile for Ubuntu 16.04 based build

### PR DESCRIPTION
**Pull request by rizwansarwar**
I could not get the alpine/default build to work, so I created a Dockerfile for Ubuntu 16.04. The image is big, but it works fine and openvpn.sh works too. May be you can add it to upstream?

### CODE REVIEW

**Comment by dperson** [comment]
What errors were you getting?

**Comment by rizwansarwar** [comment]
It was issue with OpenVPN client, I could not nail down the exact problem however the symptoms were following.

1) Container started correctly
2) Container logs show that connection VPN is successful.
3) OpenVPN would start to throw following errors, `Authenticate/Decrypt packet error: cipher final failed`
4) OpenVPN client would disconnect after about 60 seconds. It would reconnect again.
5) After about 4 retires, container died.
6) Client containers could not connect to internet.

I did not change anything in the openvpn.sh, the only change is to use Ubuntu 16.04 as base image and update to some tooling paths for Ubuntu. This has no issues and works straight away.

**Comment by rizwansarwar** [comment]
Quick note, I found the issue. The openvpn.sh does not add any ciphers to the ovpn config file. By default this might work for servers that don't require strong ciphers, however if a VPN server requires a cipher, then it is impossible to specify that. I tested this by modifying the openvpn.sh file, it worked on apline too. Maybe an environment variable to specify cipher explicitly if needed would be good to have in default image?

**Comment by rizwansarwar** [comment]
Ahhh, it is there indeed. I missed it because it is not mentioned in the README.md. Ok ignore my PR then, this is working. Thanks

**Pull request closed without merging**
