### PR TITLE
Corrected grep's \<word\> syntax for checking "ca" option

### PR DESCRIPTION
**Pull request by jest**

### CODE REVIEW

**Comment by dperson** [comment]
I'm not grepping for `\<` word break start and `\>` word break end I'm looking for the literal string `<ca>`.

**Comment by jest** [comment]
Ah, I get it, you're looking for `<ca>my_cert_content_not_the_file_name</ca>`. That's a confusion, indeed. :)

**Comment by dperson** [comment]
Yes, some VPN providers are embedding the CA certificate in the openvpn file. So I'm checking to see if it's included there.

**Comment by jest** [comment]
Do you consider adding custom `ca another_file_in_/vpn_folder` checking the same way, like:

    [[ -e $cert ]] || grep -q '<ca>' $conf || grep -q '\<ca\>' $conf ||

It would be easier for the ones like me, to whom the provider gives a folder with ovpn and certs, and everything works out of the box. Beside the error message and waiting 120s, which would be circumvented by the above additional check.

Of course I can also rename the CA cert file to `vpn_ca.crt` and change the ovpn file. But why not let it work out of the box?

**Pull request closed without merging**
