### PR TITLE
add option for conf and ca-cert files

### PR DESCRIPTION
**Pull request by StudioEtrange**
* add one option '-V' to specify our conf file and/or aour ca-cert file instead of generating it or have it with hardcoded file name

```


    -V '<[conf];[cert]>' Specify OpenVPN configuration and cert file
                required arg: ';'
                optional args:
                [conf] file inside /vpn to use for openvpn configuration
                [cert] file inside /vpn to use as cert file with ca
```

* often when using a vpn provider we can download an archive of ovpn files with a lof of files. With this option and when mounting this folder into /vpn, we can choose which files to use without renaming it to vpn.conf (or withour deleting all files but one)

### CODE REVIEW

**Comment by StudioEtrange** [comment]
There was a problem of setting order with DNS and CERT_AUTH option (or env var)
when we pass our own filenames with -V

I solved this in last commit

**Comment by StudioEtrange** [comment]
I create a new one, with commit squashed

**Comment by StudioEtrange** [comment]
New PR is #268

**Comment by dperson** [comment]
See the latest change (it's in the `README.md` and script), I think it should handle your use case of wanting to select a specific configuration file.

**Pull request closed without merging**
