### PR TITLE
Fix blocked connections from vpnportforward

### PR DESCRIPTION
**Pull request by 5andr0**
I managed to fix https://github.com/dperson/openvpn-client/issues/284

```
iptables -t nat -A OUTPUT -p $protocol --dport $port -j DNAT \
                --to-destination 127.0.0.111:$port
```
This rule is the root of all evil. It is unnecessary and breaks outgoing connections on $port.
There is no need to reroute incoming connections from the remote vpn ip to the lo interface.
The remote connections are coming in at the tun device and will reach anything that is listening on 0.0.0.0
All that's needed is to allow tun+ inputs, which i added by default in the firewall.
For anyone with concerns: client-to-client vpn connections are not possible with tun connections. Only the forward ports you configure on your vpn-server will be forwarded from the remote IP to your tun iface.

**This means:** with this patch it's unnecessary to set your vpn forward ports with VPNPORT or -p.

I left the vpnportforward function for compatibility and printing deprecated warnings, but it should be removed completely in the future since it is breaking outgoing connections and not needed at all!

Now for the second part:
I also added a global return route by default.
This allows the services to be reached from any network including the public internet! (given that the ports are exposed on the docker container)

**Advantages:**
- ROUTE/-r is deprecated and not needed anymore to manually set every local net
- there is no need for reverse proxy containers as the ports can now be reached directly
- the service ports can now be reached by any local network, that is linked on the docker host
- this allows the services to be reached on a VPS over its public ip without the need of reverse proxies

I also left the deprecated return_route functions for compatibility with a deprecated warning:
`echo "The use of ROUTE or -r is deprecated and not needed anymore!"`

I suggest to merge this fix with the compatibility.
After a while you can then update the readme and remove the section about reverse proxy containers and wipe the vpnportforward code and all notes about VPNPORT / -p. 
I would also remove notes about ROUTE / -r, but leave the code for compatibility.

What are your thoughts?

Btw: It would be good to have a note in the readme that it's necessary to restart all attached containers if the vpn container is updated or restarted. Their link will be lost, which is by design of docker.

### CODE REVIEW

**Comment by dperson** [comment]
A few questions / issues with this:

**Allowing all traffic from the VPN**:
```
    iptables -A INPUT -i tap+ -j ACCEPT
    iptables -A INPUT -i tun+ -j ACCEPT
```
* Not a fan of this, and unlikely to be merged. Services that people run using the container are often there and listening on specific ports, and not necessarily secured for being accessible from the internet. They intend them to be local access only.

**global_return_routes**:
```
    ip=$(hostname -i)
...
    ip rule add from $ip lookup 10
    ip route add default via $gw table 10
    iptables -A INPUT -d $ip -j ACCEPT
```
1. I'm pretty sure that `hostname -i` returns all non-loopback IPs (IPv4 and IPv6) that a system has...
1. I haven't done a lot with `ip rule`, and maybe I'm misunderstanding `from $ip` but normally 'from' normally indicates the sending system. So if I understand correctly (and I may not), you're adding a routing rule that will trigger when the system is going to send traffic from it's docker assigned IP? If the local network the docker server is on is `192.168.1.0/24`, the docker network is `10.0.0.0/16`, and the VPN will give you `3.16.0.123/24` (all made up), once everything is up and your `ip rule` and `ip route` are in place, how does it know where to route return traffic for `192.168.1.0/24` (which is what the `-R` / `-r` / `ROUTE6` / `ROUTE` are for)?

**vpnportforward**:
* If the NATs are breaking things why don't we just get rid of the NATs? I honestly can't remember why I'd put them in there right now, and I'm not sure they're needed... If they are needed on the systems that don't support `-i tun+` on `OUTPUT` rules, the script should just fail to open them instead. But I do want people to have to **specifically and explicitly** tell the container to allow the internet to be able to access a port.

**Comment by 5andr0** [comment]
**Allowing all traffic from the VPN:**
I know these rules look terrifyingly open, but actually they are not.
Let me explain:
- client-to-client communication is not available with tun and even if somebody got tap to work with this image (which doesn't work by default) it would require extensive routing (that the user would have to set up anyway and is in control) to ever be reached by other clients
- so the only ever incoming traffic is from ports that have been manually forwarded by your openvpn-server
- to reach your vpn client over tun the user has to configure and **explicitly** and **willingly** open these ports manually on the vpn server side
- that means: the only incoming connections on these interfaces have already been approved by the user
- so why would the user have to also manually allow the port in the client if he already opened and approved it in his server config?
- i don't see any security concern here and i'm all about security. But convenience is key in this case!

**global_return_routes:**
1. You might be right, i thought i already tested it within alpine with 2 container networks and came to the conclusion that the alpine implementation of hostname only prints the default gateway IP. But i will check again and find an alternative which definitely only returns the docker net ip.
2. Incoming connections over the docker (or kubernetes) exposed ports are already routed to the container docker net ip over the default docker net gateway. Only the route back is missing and added by these rules. So basically what happens here, if a packet is sent back FROM the docker ip it will check in the lookup table where the connection was coming from and routed back over the docker gateway to the external nets.
Just try it and be amazed by its magic. It'll work from every network linked from the host, can be multiple networks and the internet. I've already done these tests

**vpnportforward:**
Yea, just through it out. Nobody needs that. The only thing needed for reaching your service is allowing the input ports in tun+/tap+
iptables input with -i to filter on an interface is always available, just nat output -i doesn't work, but this rule is just broken and wrong.
So please rethink your stance on allowing input to tun+/tap+ by default because of the arguments above. Otherwise you would need
```
vpnportforward() { local port="$1" protocol="${2:-tcp}"
    ip6tables -A INPUT -i tun+ -p $protocol -m $protocol --dport $port -j ACCEPT \
                2>/dev/null
    ip6tables -A INPUT -i tap+ -p $protocol -m $protocol --dport $port -j ACCEPT \
                2>/dev/null
    iptables -A INPUT -i tun+ -p $protocol -m $protocol --dport $port -j ACCEPT
    iptables -A INPUT -i tap+ -p $protocol -m $protocol --dport $port -j ACCEPT
    echo "Setup forwarded port: $port $protocol"
}
```
But by all means, this is super unnecessary having to open the ports manually twice, when it already has to be done manually on the openvpn-server and otherwise wouldn't affect the security if the user doesn't open these ports on his openvpn-server

**Comment by dperson** [comment]
I actually added the blocking of inbound specifically because I got reports from users of the container that their services were being exposed. With the sheer number of VPN providers out there, I am *very* hesitant to say that none of them still have their service configured to allow access into the system behind the VPN.

I'll merge the rest of the change however. Thanks for both the patch and the explanation!

**Comment by 5andr0** [comment]
@dperson okay nice
check this commit for the right way to get ip & gw: https://github.com/5andr0/openvpn-client/commit/dd004db42e3f915b135c4b79c02f10f454b74514

```
local def_if=$(ip r |awk '/^default/{print $5}') \
    gw=$(ip r |awk '/^default/ {print $3}') \
    gw6="$(ip -6 r |awk '/^default/ {print $3}')" \
    ip=$(ip a show dev $def_if | awk -F '[ \t]+|/' '$2=="inet" {print $3}')\
    ip6=$(ip -6 a show dev $def_if | awk -F '[ \t]+|/' \
        '$2=="inet6" && $3 !~ /^fe80/ && $3 !="::1" {print $3}')
```

**Comment by dperson** [comment]
Looks like we had pretty parallel thoughts about it:
```
global_return_routes() { local if=$(ip r | awk '/^default/ {print $5; quit}') \                   
    gw="$(ip -4 r show dev eth0 | awk '/default/ {print $3}')" \                 
    gw6="$(ip -6 r show dev eth0 | awk '/default/ {print $3}')" \                
    ip=$(ip -4 a show dev eth0 | awk -F '[ \t/]+' '/inet .*global/ {print $3}')\ 
    ip6=$(ip -6 a show dev eth0 | awk -F '[ \t/]+' '/inet6.*global/ {print $3}')
```
I'm about to push the commit.

**Comment by 5andr0** [comment]
@dperson I really like your new global_return_routes code from latest commit, looks sharp!
I think my job is done here, enjoyed working on this project! 
Keep it up!

**Comment by dperson** [comment]
@5andr0 I really appreciate your contributions and help!

**Pull request closed without merging**
