### PR TITLE
Fix firewall env var typo

### PR DESCRIPTION
**Pull request by mkozjak**
@dperson - can you please also docker tag the release?

Signed-off-by: Mario Kozjak <kozjakm1@gmail.com>

### CODE REVIEW

**Comment by dperson** [comment]
Doh! thank you.

**Comment by mkozjak** [comment]
@dperson thanks for the merge! Can you please push docker tag to your repo? For example dperson/openvpn-client:<git-commit-rev>. Using “latest” in production feels sketchy. Thanks in advance!

**Comment by dperson** [comment]
Tag it with what version (the package, a made up one)? and how (manually, I don't know of a automatic way of adding incrementing version numbers)?

**Comment by mkozjak** [comment]
@dperson tagging it with the HEAD git commit rev should suffice. For example if the latest commit was df43ab5, then do a docker tag with dperson/openvpn-client:df43ab5. Then push that tag along with :latest so we have both. Sounds good?

**Comment by dperson** [comment]
Docker hub builds them and pushes them. There is no support for adding the commit rev as a tag. Again, how other than manually do I do what you want? I'm not manually tagging every build.

**Comment by mkozjak** [comment]
`https://github.com/estesp/manifest-tool` seems to support variables in manifests.
Maybe we could duplicate all entries having `<GIT_TAG>-<ARCH>`, for example `dperson/openvpn-client:7130fa2-aarch64`. Makes sense?

**Comment by mkozjak** [comment]
Also, seems like the legit thing would be to define `tags` for each image defined. That way we're avoiding duplication.

https://github.com/estesp/manifest-tool/blob/0be3561a269eb17f7b77985b51f9365c2aa820e8/README.md#functional-changelog-for-pushcreate

**Comment by dperson** [comment]
And no, this request is going off the rails. If / when it supports the git rev as a tag I'll revisit this.

**Comment by mkozjak** [comment]
Ok, makes sense!

So I guess the only way to secure the deployment is to fork the repo and push our own image with a needed tag to our docker hub account.

**Pull request merged**
